const Map<String, String> ioDataUnitMap = {
  'Total Odometer': 'km',
  'Gsm Signal': 'dBm',
  'Engine Load': '%',
  'Coolant Temperature': '°C',
  'Short Fuel Trim': '%',
  'Engine Rpm': 'rpm',
  'Vehicle Speed': 'km/h',
  'Timing Advance': '°',
  'Intake Air Temperature': '°C',
  'Maf': 'g/s',
  'Throttle Position': '%',
  'Runtime Since Engine Start': 's',
  'Distance Traveled Mil On': 'km',
  'Distance Since Codes Clear': 'km',
  'Barometric Pressure': 'kPa',
  'Control Module Voltage': 'V',
  'Ambient Air Temperature': '°C',
  'Time Run With Mil On': 'min',
  'Time Since Codes Cleared': 'min',
  'External Voltage': 'V',
  'Battery Voltage': 'V',
  'Battery Current': 'A',
  'Gnss Pdop': '',
  'Gnss Hdop': '',
  'Fuel Type': '',
  'Sleep Mode': '',
  'Movement': '',
  'Ignition': '',
};
